steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/easylistbot/easylistbot:latest', '.']
  
  # ビルドしたイメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/easylistbot/easylistbot:latest']

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/easylistbot/easylistbot:latest'
